import sys
from pathlib import Path

# Adjust path to enable imports from project root
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import pandas as pd  # noqa: E402

from src.data.load import load_table_1  # noqa: E402
from src.data.clean import (  # noqa: E402
    clean,
    DEFAULT_INPUT,
    DEFAULT_OUTPUT,
)
from src.data.transform import (  # noqa: E402
    harmonise_columns,
    normalise_quarter_label,
    annotate_coverage,
)

# Paths
QUARTERLY_OUTPUT = (
    project_root / "data" / "interim" / "visitors_by_quarter.csv"
)


def make_visitors_by_quarter(
    input_path: Path | str = DEFAULT_INPUT,
    cleaned_output_path: Path | str = DEFAULT_OUTPUT,
):
    """Generate quarterly visitors CSV using the full src pipeline.

    This explicitly runs the cleaning step using:
      - src.data.clean.clean
      - src.data.clean.DEFAULT_INPUT (default input)
      - src.data.clean.DEFAULT_OUTPUT (default cleaned output)

    Parameters
    ----------
    input_path : Path | str
        Path to the raw input used by the cleaning step
        (defaults to DEFAULT_INPUT).
    cleaned_output_path : Path | str
        Path to the cleaned output generated by the cleaning step
        (defaults to DEFAULT_OUTPUT).
    """
    print("🔄 Starting visitors_by_quarter generation...")

    # 0) Ensure the cleaned dataset is (re)generated using the canonical
    #    clean() entrypoint
    print(
        f"🧼 Cleaning data from {input_path} -> {cleaned_output_path} ..."
    )
    clean(input_path, cleaned_output_path)

    # 1) Load the cleaned data using the specialized loader
    print("📥 Loading cleaned Table 1 data...")
    df = load_table_1()

    if df.empty:
        raise ValueError("Failed to load Table 1 data")

    # 2) Select and rename columns for our specific use case
    df = df.rename(columns={"Period": "period", "World total": "visits"})
    df = df[["period", "visits"]].copy()

    # 3) Use transform module functions for standardization
    print("🔧 Applying data transformation...")
    df = harmonise_columns(df)

    # Normalize quarter labels using transform function
    df["quarter"] = df["period"].astype(str).apply(
        normalise_quarter_label
    )

    # Extract year from normalized quarter
    df["year"] = (
        df["quarter"]
        .astype(str)
        .str.extract(r"(\d{4})")[0]
        .astype("Int64")
    )

    # Add coverage annotation (UK vs GB, etc.)
    df = annotate_coverage(df)

    # 4) Clean numeric values
    df["visits"] = pd.to_numeric(df["visits"], errors="coerce")

    # 5) Filter for quarterly data only (exclude annual totals)
    quarterly_mask = df["period"].astype(str).str.contains("Q", na=False)
    df_quarterly = df[quarterly_mask].copy()

    if df_quarterly.empty:
        print("⚠️ No quarterly rows found after filtering.")
        # Still write an empty CSV with headers so downstream steps don't fail
        QUARTERLY_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(
            columns=[
                "year",
                "quarter",
                "period_q",
                "visits_thousands",
                "coverage",
            ]
        ).to_csv(QUARTERLY_OUTPUT, index=False)
        return pd.DataFrame()

    # 6) Create period_q in the desired format
    quarter_num = df_quarterly["quarter"].astype(str).str.extract(r"Q(\d)")[0]
    df_quarterly["period_q"] = (
        df_quarterly["year"].astype(str) + " Q" + quarter_num
    )

    # 7) Select, sort, and rename final columns
    visitors_by_quarter = df_quarterly[
        ["year", "quarter", "period_q", "visits", "coverage"]
    ].rename(columns={"visits": "visits_thousands"})

    visitors_by_quarter = visitors_by_quarter.sort_values(
        ["year", "quarter"]
    ).reset_index(drop=True)

    visitors_by_quarter = visitors_by_quarter.dropna(
        subset=["visits_thousands"]
    )

    # 8) Write CSV
    QUARTERLY_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    visitors_by_quarter.to_csv(QUARTERLY_OUTPUT, index=False)

    # Print summary (keep lines short for linting)
    print(f"✅ Wrote {QUARTERLY_OUTPUT}")
    print(f"📊 Rows: {len(visitors_by_quarter)}")
    if not visitors_by_quarter.empty:
        print(
            "📅 Date range: "
            f"{visitors_by_quarter['period_q'].min()} to "
            f"{visitors_by_quarter['period_q'].max()}"
        )
        print(
            "🌍 Coverage: "
            f"{visitors_by_quarter['coverage'].value_counts().to_dict()}"
        )
        total_visits = visitors_by_quarter[
            "visits_thousands"
        ].sum(skipna=True)
        print(f"🔢 Total visits (thousands): {total_visits:,.0f}")

    return visitors_by_quarter


if __name__ == "__main__":
    make_visitors_by_quarter()
